name: Build and Push Docker Image
#comment
on:
  push:
    branches:
      - master # Or the branch you want to trigger the action on

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image (GPU)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile # Path to your Dockerfile
        push: true
        tags: |
          YOUR_DOCKER_HUB_USERNAME/realtime-stt:latest
          YOUR_DOCKER_HUB_USERNAME/realtime-stt:${{ github.sha }}
        platforms: linux/amd64 # Specify the target platform
        target: gpu # Specify the target stage in your Dockerfile
